[manifest]
version = "1.0.0"
dump_lua = true
priority = 0


[[patches]]
[patches.pattern]
target = "back.lua"
pattern = "if self.name == 'Plasma Deck' and args.context == 'final_scoring_step' then"
position = "before"
payload = '''
local is_der_richter_exists = function()
	local der_richter_card = SMODS.find_card("j_surtr_der_richter")
	if der_richter_card ~= {} then
		return true
	end
	return false
end
local calculate_balance = function()
	return is_der_richter_exists()
end
'''
match_indent = true
overwrite = false

[[patches]]
[patches.pattern]
target = "back.lua"
pattern = "if self.name == 'Plasma Deck' and args.context == 'final_scoring_step' then"
position = "at"
payload = '''
if ((self.name == 'Plasma Deck') and args.context == 'final_scoring_step') or (is_der_richter_exists() and args.context == "joker_main") then
'''
match_indent = true
overwrite = true

[[patches]]
[patches.pattern]
target = "back.lua"
pattern = """
                attention_text({
                    scale = 1.4, text = text, hold = 2, align = 'cm', offset = {x = 0,y = -2.7},major = G.play
                })
"""
position = "at"
payload = '''
if args.context == 'final_scoring_step' then
	attention_text({
		scale = 1.4, text = text, hold = 2, align = 'cm', offset = {x = 0,y = -2.7},major = G.play
	})
else 
	attention_text({
		scale = 0, text = text, hold = 2, align = 'cm', offset = {x = 0,y = -2.7},major = G.play
	})
end
'''
match_indent = true
overwrite = true

# payload = '''
# if (self.name == 'Plasma Deck' or (G.GAME.VictinsCollection and G.GAME.VictinsCollection.equalize)) and args.context == 'final_scoring_step' then
# ''